/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesWebDevelopmentRouteImport } from './routes/courses.web-development'
import { Route as CoursesUiUxDesignRouteImport } from './routes/courses.ui-ux-design'
import { Route as CoursesPythonRouteImport } from './routes/courses.python'
import { Route as CoursesMobileAppDevRouteImport } from './routes/courses.mobile-app-dev'
import { Route as CoursesGameDevScratchRouteImport } from './routes/courses.game-dev-scratch'
import { Route as CoursesGameDevRobloxRouteImport } from './routes/courses.game-dev-roblox'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesWebDevelopmentRoute = CoursesWebDevelopmentRouteImport.update({
  id: '/web-development',
  path: '/web-development',
  getParentRoute: () => CoursesRoute,
} as any)
const CoursesUiUxDesignRoute = CoursesUiUxDesignRouteImport.update({
  id: '/ui-ux-design',
  path: '/ui-ux-design',
  getParentRoute: () => CoursesRoute,
} as any)
const CoursesPythonRoute = CoursesPythonRouteImport.update({
  id: '/python',
  path: '/python',
  getParentRoute: () => CoursesRoute,
} as any)
const CoursesMobileAppDevRoute = CoursesMobileAppDevRouteImport.update({
  id: '/mobile-app-dev',
  path: '/mobile-app-dev',
  getParentRoute: () => CoursesRoute,
} as any)
const CoursesGameDevScratchRoute = CoursesGameDevScratchRouteImport.update({
  id: '/game-dev-scratch',
  path: '/game-dev-scratch',
  getParentRoute: () => CoursesRoute,
} as any)
const CoursesGameDevRobloxRoute = CoursesGameDevRobloxRouteImport.update({
  id: '/game-dev-roblox',
  path: '/game-dev-roblox',
  getParentRoute: () => CoursesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/courses/game-dev-roblox': typeof CoursesGameDevRobloxRoute
  '/courses/game-dev-scratch': typeof CoursesGameDevScratchRoute
  '/courses/mobile-app-dev': typeof CoursesMobileAppDevRoute
  '/courses/python': typeof CoursesPythonRoute
  '/courses/ui-ux-design': typeof CoursesUiUxDesignRoute
  '/courses/web-development': typeof CoursesWebDevelopmentRoute
  '/courses/': typeof CoursesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/courses/game-dev-roblox': typeof CoursesGameDevRobloxRoute
  '/courses/game-dev-scratch': typeof CoursesGameDevScratchRoute
  '/courses/mobile-app-dev': typeof CoursesMobileAppDevRoute
  '/courses/python': typeof CoursesPythonRoute
  '/courses/ui-ux-design': typeof CoursesUiUxDesignRoute
  '/courses/web-development': typeof CoursesWebDevelopmentRoute
  '/courses': typeof CoursesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/courses/game-dev-roblox': typeof CoursesGameDevRobloxRoute
  '/courses/game-dev-scratch': typeof CoursesGameDevScratchRoute
  '/courses/mobile-app-dev': typeof CoursesMobileAppDevRoute
  '/courses/python': typeof CoursesPythonRoute
  '/courses/ui-ux-design': typeof CoursesUiUxDesignRoute
  '/courses/web-development': typeof CoursesWebDevelopmentRoute
  '/courses/': typeof CoursesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/courses/game-dev-roblox'
    | '/courses/game-dev-scratch'
    | '/courses/mobile-app-dev'
    | '/courses/python'
    | '/courses/ui-ux-design'
    | '/courses/web-development'
    | '/courses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/courses/game-dev-roblox'
    | '/courses/game-dev-scratch'
    | '/courses/mobile-app-dev'
    | '/courses/python'
    | '/courses/ui-ux-design'
    | '/courses/web-development'
    | '/courses'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/courses/game-dev-roblox'
    | '/courses/game-dev-scratch'
    | '/courses/mobile-app-dev'
    | '/courses/python'
    | '/courses/ui-ux-design'
    | '/courses/web-development'
    | '/courses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/web-development': {
      id: '/courses/web-development'
      path: '/web-development'
      fullPath: '/courses/web-development'
      preLoaderRoute: typeof CoursesWebDevelopmentRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/courses/ui-ux-design': {
      id: '/courses/ui-ux-design'
      path: '/ui-ux-design'
      fullPath: '/courses/ui-ux-design'
      preLoaderRoute: typeof CoursesUiUxDesignRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/courses/python': {
      id: '/courses/python'
      path: '/python'
      fullPath: '/courses/python'
      preLoaderRoute: typeof CoursesPythonRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/courses/mobile-app-dev': {
      id: '/courses/mobile-app-dev'
      path: '/mobile-app-dev'
      fullPath: '/courses/mobile-app-dev'
      preLoaderRoute: typeof CoursesMobileAppDevRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/courses/game-dev-scratch': {
      id: '/courses/game-dev-scratch'
      path: '/game-dev-scratch'
      fullPath: '/courses/game-dev-scratch'
      preLoaderRoute: typeof CoursesGameDevScratchRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/courses/game-dev-roblox': {
      id: '/courses/game-dev-roblox'
      path: '/game-dev-roblox'
      fullPath: '/courses/game-dev-roblox'
      preLoaderRoute: typeof CoursesGameDevRobloxRouteImport
      parentRoute: typeof CoursesRoute
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
